app.py
from flask import Flask,blueprints
#Blueprint
from routes import main_route,market_view_route

app = Flask(__name__)

app.register_blueprint(main_route.index)
app.register_blueprint(market_view_route.market)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port='5000', debug=True)

routes/main_route.py
from flask import Blueprint, render_template

from infrastructure import index_render, usd_positions, usd_balance,usd_open_orders

index = Blueprint('index', __name__, url_prefix='/')

@index.route('/')
def index_route():
    balance = usd_balance.usd_balance()
    positions = usd_positions.usd_position()
    open_orders = usd_open_orders.usd_orders()
    return render_template(index_render.index_view(), balance=[balance], positions=positions, open_orders=open_orders)

routes/market_view_route.py
from flask import Blueprint, render_template

from infrastructure import market_view_render,order_view_render,\
    usd_fetch_markets, order_options

market = Blueprint('market', __name__, url_prefix='/')

@market.route('/market')
def market_route():
    perp_dict = usd_fetch_markets.fetch_perp_markets()
    return render_template(market_view_render.market_view(),
                           perp_dict = perp_dict,
                           symbols = order_options.symbols,
                           positions = order_options.positions,
                           qty = order_options.qty,
                           )


# @market.route('/order/')
# def order_options():
#     symbols = order_options.symbol
#     return render_template(order_view_render.order_view(), symbols = symbols)

templates/index.html
{% extends 'layout.html' %}
{% block body %}
  <h3 class='text-center text-muted mb-3'>Flask - SQLite CRUD Application</h3>
  <p class='text-right'><a href='{{url_for("market.market_route")}}' class='btn btn-success '>-> Market view</a></p>
  <table class='table table-bordered'>
    Balance
    <thead>
      <th>No.</th>
      <th>USD</th>
      <th>BTC</th>
      <th>ETH</th>
      <th>XRP</th>
    </thead>
    <tbody>
      {% for row in balance %}
        <tr>
          <td>{{loop.index}}</td>
          <td>{{row.USD}} USD</td>
          <td>{{row.BTC}} BTC</td>
          <td>{{row.ETH}} ETH</td>
          <td>{{row.XRP}} XRP</td>
        </tr>
      {%endfor%}
    </tbody>
  </table>
<table class='table table-bordered'>
  Positions
<thead>
  <th>No.</th>
  <th>Future</th>
  <th>National size</th>
  <th>Size</th>
  <th>Side</th>
  <th>EntryPrice</th>
  <th>RecentPnl</th>
</thead>
<tbody>
  {% for row in positions %}
    <tr>
      <td>{{loop.index}}</td>
      <td>{{row.future}} </td>
      <td>{{row.cost}} USD</td>
      <td>{{row.size}}</td>
      <td>{{row.side}} </td>
      <td>{{row.entryPrice}} USD </td>
      <td>{{row.recentPnl}} USD </td>
      <td><a href='{{url_for("index.index_route",USD=row.USD)}}' class='btn btn-primary'>Edit</a></td>
      <td><a href='{{url_for("index.index_route",USD=row.USD)}}' class='btn btn-danger' onclick='return confirm("Are You Sure?")'>Delete</a></td>
    </tr>
  {%endfor%}
</tbody>
</table>
<table class='table table-bordered'>
  Open orders
<thead>
  <th>No.</th>
  <th>Future</th>
  <th>OrderPrice</th>
  <th>size</th>
  <th>type</th>
  <th>Side</th>
</thead>
<tbody>
  {% for row in open_orders %}
    <tr>
      <td>{{loop.index}}</td>
      <td>{{row.market}}</td>
      <td>{{row.price}} USD</td>
      <td>{{row.size}}</td>
      <td>{{row.type}}</td>
      <td>{{row.side}}</td>
      <td><a href='{{url_for("index.index_route",USD=row.USD)}}' class='btn btn-primary'>Edit</a></td>
      <td><a href='{{url_for("index.index_route",USD=row.USD)}}' class='btn btn-danger' onclick='return confirm("Are You Sure?")'>Delete</a></td>
    </tr>
  {%endfor%}
</tbody>
</table>
{% endblock %}

templates/layout.html
<html>
  <head>
    <title>Flask - SQLite </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <body>
    <div class='container pt-3'>
      {% with messages=get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category,message in messages %}
            <div class='alert alert-{{category}}'>{{message}}</div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {% block body %}

      {% endblock %}
    </div>
  </body>
</html>

templates/market_view.html
{% extends 'layout.html' %}
{% block body %}
  <h3 class='text-center text-muted mb-3'>Flask - SQLite CRUD Application</h3>
  <p class='text-right'><a href='{{url_for("index.index_route")}}' class='btn btn-success '>+Add </a></p>
  <table class='table table-bordered'>
    Rank
    <thead>
    <th>No.</th>
    <th>Symbol</th>
    <th>changeBod </th>
    <th>change1h </th>
    <th>change24h </th>
    <th>volumeUsd24h </th>
    </thead>
    {% for row in perp_dict %}
    <thead>
    <th>{{loop.index}}</th>
    <th>{{row.name}}</th>
    <th>{{row.changeBod}} %</th>
    <th>{{row.change1h}} %</th>
    <th>{{row.change24h}} %</th>
    <th>{{row.volumeUsd24h}} USD</th>
    </thead>
    {%endfor%}
  </table>
{% block order %}
    {% include "order_options.html" %}
{% endblock order %}
{% endblock %}

templates/order_options.html
<!doctype html>
<html lang="en">
      <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
      <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <h3>order</h3>
      <select class="selectcoin">
        {% for row in symbols %}
          <option>{{row}}</option>
        {%endfor%}
      </select>
      <select class="selectcoin">
        {% for row in qty %}
          <option>{{row}}</option>
        {%endfor%}
      </select>
      <select class="selectcoin">
        {% for row in positions %}
          <option>{{row}}</option>
        {%endfor%}
      </select>

  </body>

</html>